In [1]:
import sympy as sym
from IPython.display import display, Math

In [2]:
x = sym.symbols('x')

expr = 2*x + 4 - 9

In [3]:
sym.solve(expr, x)

[5/2]

In [4]:
display(Math('\\text{The solution is } %s \\text{ is x= } %g' % (sym.latex(expr), sym.solve(expr)[0])))

<IPython.core.display.Math object>

In [5]:
sol = sym.solve(x**2 -4)

type(sol)
len(sol)
print(sol)

[-2, 2]


In [6]:
expr = x**2 - 4
sol = sym.solve(expr)

for i in range(len(sol)):
    print('Solution # ' + str(i+1) + ' is ' + str(sol[i]))

Solution # 1 is -2
Solution # 2 is 2


In [7]:
x, y = sym.symbols('x, y')
expr = x/4 - x*y + 5
sym.solve(expr, y)

[(x + 20)/(4*x)]

In [8]:
q = sym.symbols('q')
expr = 3*q + 4/q + 3 - (5*q + 1/q +1)

In [9]:
sym.simplify(expr)

-2*q + 2 + 3/q

In [10]:
display(Math(sym.latex(sym.solve(expr, q))))

<IPython.core.display.Math object>

In [11]:
expr1 = 2*q + 3*q**2 - 5/q - 4/q**3
sym.simplify(expr1)

3*q**2 + 2*q - 5/q - 4/q**3

In [12]:
sym.cancel(expr1)

(3*q**5 + 2*q**4 - 5*q**2 - 4)/q**3

In [13]:
sym.solve(expr1, q)

[CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 0),
 CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 1),
 CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 2),
 CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 3),
 CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 4)]

In [14]:
expr2 = (sym.sqrt(3) + sym.sqrt(15)*q)/(sym.sqrt(2) + sym.sqrt(10)*q)

In [15]:
display(Math(sym.latex(sym.simplify(expr2))))

<IPython.core.display.Math object>

In [16]:
expr2.subs(q, 1).evalf()

1.22474487139159

In [18]:
expr2.subs(q, 1000000).evalf()

1.22474487139159

In [19]:
term1 = (4*x + 5)
term2 = x

print(term1 * term2)

x*(4*x + 5)


In [20]:
print(sym.expand(term1*term2))

4*x**2 + 5*x


In [21]:
display(Math(sym.latex(sym.expand(term1*term2))))

<IPython.core.display.Math object>

In [22]:
term3 = x-7

display(Math(sym.latex(term1*term3)))

<IPython.core.display.Math object>

In [24]:
display(Math(sym.latex(sym.expand(term1*term3))))

<IPython.core.display.Math object>

In [25]:
y = sym.symbols('y')

In [27]:
expr = x*(2*y**2 - 5**x/x)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.expand(expr))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [28]:
%whos

Variable   Type        Data/Info
--------------------------------
Math       type        <class 'IPython.core.display.Math'>
display    function    <function display at 0x000001523214E940>
expr       Mul         x*(-5**x/x + 2*y**2)
expr1      Add         3*q**2 + 2*q - 5/q - 4/q**3
expr2      Mul         (sqrt(15)*q + sqrt(3))/(sqrt(10)*q + sqrt(2))
i          int         1
q          Symbol      q
sol        list        n=2
sym        module      <module 'sympy' from 'C:\<...>ges\\sympy\\__init__.py'>
term1      Add         4*x + 5
term2      Symbol      x
term3      Add         x - 7
x          Symbol      x
y          Symbol      y


In [39]:
x, y = sym.symbols('x, y')

expr = (4 + x)*(2 - y)

numrange = range(3)

for xi in numrange:
    for yi in numrange:
        print('When x = %g and y = %g, f(x, y) = %g' % (xi, yi, expr.subs({x:xi, y:yi})))
        

When x = 0 and y = 0, f(x, y) = 8
When x = 0 and y = 1, f(x, y) = 4
When x = 0 and y = 2, f(x, y) = 0
When x = 1 and y = 0, f(x, y) = 10
When x = 1 and y = 1, f(x, y) = 5
When x = 1 and y = 2, f(x, y) = 0
When x = 2 and y = 0, f(x, y) = 12
When x = 2 and y = 1, f(x, y) = 6
When x = 2 and y = 2, f(x, y) = 0


In [1]:
import numpy as np
import sympy as sym
from IPython.display import display, Math

In [4]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
type(A)

numpy.ndarray

In [6]:
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

In [8]:
mat = np.zeros([4, 6])

In [14]:
mat[0, 1] = 2
mat[2, 4] = 7

In [15]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [19]:
numrange = range(4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi, coli] = (-1)**(rowi+coli)
        
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [31]:
x, y = sym.symbols('x, y')

numrange = range(3)

expr = (4 + x)*(2 - y)

mat = np.zeros([len(numrange), len(numrange)])
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
for xi in numrange:
    for yi in numrange:
        mat[xi, yi] = expr.subs({x:xi, y:yi})

In [33]:
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [63]:
# create a multiplication table
x, y = sym.symbols('x y')

numrange = range(10)

table = np.zeros([len(numrange), len(numrange)], dtype=int)
table

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [64]:
for i in numrange:
    for j in numrange:
        table[i, j] = (i+1)*(j+1)

In [65]:
display(Math(sym.latex(sym.sympify(table))))

<IPython.core.display.Math object>

In [1]:
import sympy as sym

In [2]:
x, y = sym.symbols('x y')
expr1 = x*(4*y)
expr2 = (x*4)*y

In [4]:
sym.Eq(expr1, expr2)

True

In [6]:
e1 = 4*x*y
e2 = x*4*y
e3 = y*x*4

In [7]:
e1.subs({x:3, y:2})

24

In [8]:
e2.subs({x:3, y:2})

24

In [9]:
e3.subs({x:3, y:2})

24

In [10]:
a, b, c, d = sym.symbols('a b c d')
expr = (a+b)*(c+d)

In [11]:
sym.expand(expr)

a*c + a*d + b*c + b*d

In [12]:
x, y, z, w = sym.symbols('x, y, z, w')

In [21]:
x = w*(4-w)+1/w**2
f1 = x*(y+z)
f2 = 3/x + x**2


In [22]:
sym.expand(f1)

-w**2*y - w**2*z + 4*w*y + 4*w*z + y/w**2 + z/w**2

In [23]:
sym.expand(f2)

w**4 - 8*w**3 + 16*w**2 - 2 + 3/(-w**2 + 4*w + w**(-2)) + 8/w + w**(-4)

In [24]:
sym.expand(x)

-w**2 + 4*w + w**(-2)

In [25]:
sym.simplify(x)

(w**3*(4 - w) + 1)/w**2

In [26]:
f1*f2

(y + z)*(w*(4 - w) + w**(-2))*((w*(4 - w) + w**(-2))**2 + 3/(w*(4 - w) + w**(-2)))

In [27]:
sym.simplify(f1*f2)

(3*w**6 - (w**3*(w - 4) - 1)**3)*(y + z)/w**6

In [28]:
sym.expand(f1*f2)

-w**6*y - w**6*z + 12*w**5*y + 12*w**5*z - 48*w**4*y - 48*w**4*z + 64*w**3*y + 64*w**3*z + 3*w**2*y - 3*w**2*y/(-w**2 + 4*w + w**(-2)) + 3*w**2*z - 3*w**2*z/(-w**2 + 4*w + w**(-2)) - 24*w*y + 12*w*y/(-w**2 + 4*w + w**(-2)) - 24*w*z + 12*w*z/(-w**2 + 4*w + w**(-2)) + 48*y + 3*y/(-w**4 + 4*w**3 + 1) + 48*z + 3*z/(-w**4 + 4*w**3 + 1) - 3*y/w**2 - 3*z/w**2 + 12*y/w**3 + 12*z/w**3 + y/w**6 + z/w**6

In [30]:
f2*f1 - f1*f2

0

In [10]:
lst = [1, 3, 6, 7, 4, 5, 6, 1, 3, 5, 6, 4, 0]

In [3]:
lst

[1, 3, 6, 7]

In [4]:
type(lst)

list

In [6]:
lst[-1]

7

In [8]:
lst[:2]

[1, 3]

In [9]:
lst[2:]

[6, 7]

In [11]:
n = 3
k = 7

print(lst)
lst[n:k]

[1, 3, 6, 7, 4, 5, 6, 1, 3, 5, 6, 4, 0]


[7, 4, 5, 6]

In [12]:
words = ['hello', 'my', 'name', 'is', 'Mike']

In [13]:
for i in words:
    print(i)

hello
my
name
is
Mike


In [15]:
alist = [1, 2, 'cookies', [6, 4]]

for i in alist:
    print(i)

1
2
cookies
[6, 4]


In [16]:
alist[-1]

[6, 4]

In [17]:
alist[-1][0]

6

In [18]:
import sympy as sym
from IPython.display import display, Math

In [19]:
x = sym.symbols('x')

In [20]:
e1 = 2*x + x*(4-6*x) + x
e2 = -x*(2/x+4/x**2) + (4+x)/(4*x)
e3 = (x+3)*(x-3)*x*(1/(9*x))

In [27]:
elist = [e1, e2, e3]
for exp in elist:
    display(Math(sym.latex(exp)))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [25]:
for expr in elist:
    #display(Math(sym.latex(sym.simplify(expr))))
    display(Math(sym.latex(sym.expand(expr))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [29]:
vec = list(range(10, 21))

In [ ]:
vec