In [1]:
import sympy as sym
from IPython.display import display, Math

In [2]:
x = sym.symbols('x')

expr = 2*x + 4 - 9

In [3]:
sym.solve(expr, x)

[5/2]

In [4]:
display(Math('\\text{The solution is } %s \\text{ is x= } %g' % (sym.latex(expr), sym.solve(expr)[0])))

<IPython.core.display.Math object>

In [5]:
sol = sym.solve(x**2 -4)

type(sol)
len(sol)
print(sol)

[-2, 2]


In [6]:
expr = x**2 - 4
sol = sym.solve(expr)

for i in range(len(sol)):
    print('Solution # ' + str(i+1) + ' is ' + str(sol[i]))

Solution # 1 is -2
Solution # 2 is 2


In [7]:
x, y = sym.symbols('x, y')
expr = x/4 - x*y + 5
sym.solve(expr, y)

[(x + 20)/(4*x)]

In [8]:
q = sym.symbols('q')
expr = 3*q + 4/q + 3 - (5*q + 1/q +1)

In [9]:
sym.simplify(expr)

-2*q + 2 + 3/q

In [10]:
display(Math(sym.latex(sym.solve(expr, q))))

<IPython.core.display.Math object>

In [11]:
expr1 = 2*q + 3*q**2 - 5/q - 4/q**3
sym.simplify(expr1)

3*q**2 + 2*q - 5/q - 4/q**3

In [12]:
sym.cancel(expr1)

(3*q**5 + 2*q**4 - 5*q**2 - 4)/q**3

In [13]:
sym.solve(expr1, q)

[CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 0),
 CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 1),
 CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 2),
 CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 3),
 CRootOf(3*x**5 + 2*x**4 - 5*x**2 - 4, 4)]

In [14]:
expr2 = (sym.sqrt(3) + sym.sqrt(15)*q)/(sym.sqrt(2) + sym.sqrt(10)*q)

In [15]:
display(Math(sym.latex(sym.simplify(expr2))))

<IPython.core.display.Math object>

In [16]:
expr2.subs(q, 1).evalf()

1.22474487139159

In [18]:
expr2.subs(q, 1000000).evalf()

1.22474487139159

In [19]:
term1 = (4*x + 5)
term2 = x

print(term1 * term2)

x*(4*x + 5)


In [20]:
print(sym.expand(term1*term2))

4*x**2 + 5*x


In [21]:
display(Math(sym.latex(sym.expand(term1*term2))))

<IPython.core.display.Math object>

In [22]:
term3 = x-7

display(Math(sym.latex(term1*term3)))

<IPython.core.display.Math object>

In [24]:
display(Math(sym.latex(sym.expand(term1*term3))))

<IPython.core.display.Math object>

In [25]:
y = sym.symbols('y')

In [27]:
expr = x*(2*y**2 - 5**x/x)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.expand(expr))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [28]:
%whos

Variable   Type        Data/Info
--------------------------------
Math       type        <class 'IPython.core.display.Math'>
display    function    <function display at 0x000001523214E940>
expr       Mul         x*(-5**x/x + 2*y**2)
expr1      Add         3*q**2 + 2*q - 5/q - 4/q**3
expr2      Mul         (sqrt(15)*q + sqrt(3))/(sqrt(10)*q + sqrt(2))
i          int         1
q          Symbol      q
sol        list        n=2
sym        module      <module 'sympy' from 'C:\<...>ges\\sympy\\__init__.py'>
term1      Add         4*x + 5
term2      Symbol      x
term3      Add         x - 7
x          Symbol      x
y          Symbol      y


In [39]:
x, y = sym.symbols('x, y')

expr = (4 + x)*(2 - y)

numrange = range(3)

for xi in numrange:
    for yi in numrange:
        print('When x = %g and y = %g, f(x, y) = %g' % (xi, yi, expr.subs({x:xi, y:yi})))
        

When x = 0 and y = 0, f(x, y) = 8
When x = 0 and y = 1, f(x, y) = 4
When x = 0 and y = 2, f(x, y) = 0
When x = 1 and y = 0, f(x, y) = 10
When x = 1 and y = 1, f(x, y) = 5
When x = 1 and y = 2, f(x, y) = 0
When x = 2 and y = 0, f(x, y) = 12
When x = 2 and y = 1, f(x, y) = 6
When x = 2 and y = 2, f(x, y) = 0


In [1]:
import numpy as np
import sympy as sym
from IPython.display import display, Math

In [4]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
type(A)

numpy.ndarray

In [6]:
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

In [8]:
mat = np.zeros([4, 6])

In [14]:
mat[0, 1] = 2
mat[2, 4] = 7

In [15]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [19]:
numrange = range(4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi, coli] = (-1)**(rowi+coli)
        
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [31]:
x, y = sym.symbols('x, y')

numrange = range(3)

expr = (4 + x)*(2 - y)

mat = np.zeros([len(numrange), len(numrange)])
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
for xi in numrange:
    for yi in numrange:
        mat[xi, yi] = expr.subs({x:xi, y:yi})

In [33]:
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [63]:
# create a multiplication table
x, y = sym.symbols('x y')

numrange = range(10)

table = np.zeros([len(numrange), len(numrange)], dtype=int)
table

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [64]:
for i in numrange:
    for j in numrange:
        table[i, j] = (i+1)*(j+1)

In [65]:
display(Math(sym.latex(sym.sympify(table))))

<IPython.core.display.Math object>